TROOP_COSTS = {
    # 1 elixir
    "Skeletons": 1,
    "FireSpirit": 1,
    "IceSpirit": 1,
    "ElectroSpirit": 1,
    "HealSpirit": 1,
    # 2 elixir
    "Goblins": 2,
    "SpearGoblins": 2,
    "Berserker": 2,
    "Bomber": 2,
    "Bats": 2,
    "WallBreakers": 2,
    # 3 elixir
    "Knight": 3,
    "Archers": 3,
    "Minions": 3,
    "Princess": 3,
    "Miner": 3,
    "IceGolem": 3,
    "Bandit": 3,
    "RoyalGhost": 3,
    "Fisherman": 3,
    "Tombstone": 3,
    "Cannon": 3,
    "GoblinBarrel": 3,
    "Tornado": 3,
    "Log": 2,
    "Zap": 2,
    "BarbarianBarrel": 2,
    "Snowball": 2,
    "Arrows": 3,
    # 4 elixir
    "Valkyrie": 4,
    "Musketeer": 4,
    "MiniPekka": 4,
    "HogRider": 4,
    "InfernoDragon": 4,
    "BabyDragon": 4,
    "DarkPrince": 4,
    "LumberJack": 4,
    "EWiz": 4,
    "BattleRam": 4,
    "FlyingMachine": 4,
    "Fireball": 4,
    "Poison": 4,
    "Freeze": 4,
    "Tesla": 4,
    "InfernoTower": 5,
    "BombTower": 4,
    # 5 elixir
    "Wizard": 5,
    "Witch": 5,
    "BowlerCR": 5,
    "Executioner": 5,
    "Prince": 5,
    "GoblinGiant": 5,
    "Ram": 5,
    "MinionHorde": 5,
    "BarbarianHut": 5,
    "GoblinHut": 5,
    "Balloon": 5,
    "GraveYard": 5,
    "Lightning": 6,
    "Rocket": 6,
    # 6+ elixir
    "RoyalGiant": 6,
    "Giant": 5,
    "EliteBarbs": 6,
    "Sparky": 6,
    "PEKKA": 7,
    "MegaKnight": 7,
    "Golem": 8,
    "LavaHound": 7,
    "XBow": 6,
    "Mortar": 4,
    "ElixirCollector": 6,
    "3Musketeers": 9,
}
